export enum ActionType {
  CLICK = 'CLICK',

  SEND_KEYS = 'SEND_KEYS',

  SEARCH = 'SEARCH',

  SCROLL = 'SCROLL',

  HOVER = 'HOVER',

  NAVIGATE_TO = 'NAVIGATE_TO',

  NAVIGATE_BACK = 'NAVIGATE_BACK',

  NAVIGATE_FORWARD = 'NAVIGATE_FORWARD',

  NAVIGATE_REFRESH = 'NAVIGATE_REFRESH',

  ASSERT_EQUALS = 'ASSERT_EQUALS',

  ASSERT_THAT = 'ASSERT_THAT',
}
